id: LabelNoise
_target_: autrainer.augmentations.AugmentationPipeline

generator_seed: 0

pipeline:
  - autrainer.augmentations.LabelNoise:
      noise_rate: 0.1
      labels: ["New_England", "Northern", "North_Midland", "South_Midland", "Southern", "New_York_City", "Western", "Army_Brat"]
      mode: "fixed"          # or "probabilistic"
