defaults:
- _autrainer_
- _self_
device: cuda:7
results_dir: results
experiment_id: test
iterations: 5
test_augmentation:
  _target_: autrainer.augmentations.augmentation_pipeline.AugmentationPipeline
  id: test(-50)
  pipeline:
  - GaussianNoise:
      _target_: autrainer.augmentations.spectrogram_augmentations.SNR_noise
      snr: -50
      p: 1.0
      generator_seed: 0
      noise_type: StaticGaussian
hydra:
  sweeper:
    params:
      +seed: 0
      +batch_size: 64
      +learning_rate: 0.001
      dataset: TIMIT-sentencetype-16k
      model: Cnn10-32k-T
      optimizer: Adam
