defaults:
  - _aucurriculum_train_
  - _self_

results_dir: /data/chi-gpu1/go35mig/results_cur
experiment_id: default
iterations: 5
train_augmentation:
  _target_: autrainer.augmentations.augmentation_pipeline.AugmentationPipeline
  id: train(10)
  pipeline:
    - GaussianNoise:
        _target_: autrainer.augmentations.spectrogram_augmentations.SNR_noise
        snr: 10
        p: 1.0
        generator_seed: 0
test_augmentation:
  _target_: autrainer.augmentations.augmentation_pipeline.AugmentationPipeline
  id: test(10)
  pipeline:
    - GaussianNoise:
        _target_: autrainer.augmentations.spectrogram_augmentations.SNR_noise
        snr: 10
        p: 1.0
        generator_seed: 0
        noise_type: StaticGaussian

hydra:
  sweeper:
    params:
      +seed: 1
      +batch_size: 64
      +learning_rate: 0.001
      dataset: SpeechCommands-16k
      model: Cnn10
      optimizer: Adam
      curriculum: Curriculum
      curriculum/sampling: Original
      curriculum/scoring: CumulativeAccuracy
      curriculum/pacing: Logarithmic
      curriculum.pacing.initial_size: 0.2
      curriculum.pacing.final_iteration: 0.5
