defaults:
  - _autrainer_
  - _self_

device: "cuda:4"        # or 'cuda'

results_dir: results
experiment_id: default
iterations: 10

augmentation:
  _target_: autrainer.augmentations.augmentation_pipeline.AugmentationPipeline
  pipeline: [
            {
              "GaussianNoise": {
              _target_: autrainer.augmentations.spectrogram_augmentations.GaussianNoise,
              mean: 0.0,
              std: 0.1,
              p: 1.0},
              }
            ]


hydra:
  sweeper:
    params:
      +seed: 1
      +batch_size: 1024
      +learning_rate: 0.001
      dataset: SpeechCommands-16k
      model: Cnn10-32k-T
      optimizer: Adam