defaults:
  - _autrainer_
  - _self_

results_dir: results
experiment_id: default
iterations: 15
device: mps

hydra:
  sweeper:
    params:
      +seed: 1
      +batch_size: 32
      +learning_rate: 0.001
      +preprocessing: log_mel_16k
      dataset: TIMIT-sentencetype-16k
      model: Cnn10
      optimizer: Adam